# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-ast
      - id: check-builtin-literals
      - id: pretty-format-json
        args: [--no-sort-keys, --autofix]
      - id: debug-statements
      - id: detect-private-key
      - id: fix-encoding-pragma

  # reorder Python imports
  - repo: https://github.com/timothycrosley/isort
    rev: 5.5.3
    hooks:
      - id: isort
        args:
          [
            --multi-line=VERTICAL_HANGING_INDENT,
            --profile=black,
            --line-length=40,
          ]

  # format Python code with black
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  # static type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy

  # code formatting with prettier
  - repo: https://github.com/prettier/pre-commit
    rev: v2.1.2
    hooks:
      - id: prettier
        exclude_types: [json]

  # code style checker
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
